version: '3.7'

services:

  app:
    environment:
      # run flush, migrate and collectstatic in entrypoint
      DEBUG: 1
      # run the server on the test database (test_* is the default test database name in django)
      SQL_DATABASE: test_${POSTGRES_DB}
    command: python3 manage.py runserver 0.0.0.0:8000
networks:
  default:
    # Use a custom driver
    name: ${QFIELDCLOUD_DEFAULT_NETWORK}
